bank_app/urls.py
from django.urls import path
from . import views
from .api import BankToBankTransfer
from django.views.generic import RedirectView

app_name = 'bank_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('customer/', views.customerPortal, name='customer_portal'),
    path('<int:pk>/', views.accountDetails, name='account_details'),
    path('movement/<int:pk>/', views.movementDetails, name='movement_details'),
    path('create_account/', views.createAccount, name='create_account'),
    path('staff_customer_view/<int:pk>/', views.staffCustomerView, name='staff_customer_view'),
    path('create_customer/', views.createCustomer, name='create_customer'),
    # redirect to customer view when two-factor is complete
    path('account/two_factor/setup/complete/', RedirectView.as_view(url='/customer/')),
    path('make_transfer/', views.make_transfer, name='make_transfer'),
    path('internal_transfer', views.internal_transfer, name='internal_transfer'),
    path('bank_to_bank_transfer', views.bank_to_bank_transfer, name='bank_to_bank_transfer'),
    path('transaction_details/<int:transactionId>/', views.make_transfer, name='transaction_details'),
    path('staff_portal/', views.staffPortal, name='staff_portal'),
    path('staff_search/', views.staffSearch, name='staff_search'),
    path('take_loan/', views.take_loan, name='take_loan'),
    path('approve_loans/', views.approve_loan, name='staff_approve_loans'),
    path('approve/<int:pk>/', views.approve, name='approve'),
    path('decline/<int:pk>/>', views.decline, name='decline'),
    path('api/bank_to_bank/', BankToBankTransfer.as_view()),
]

bank_project/urls.py
from django.contrib import admin
from django.urls import path, include
from two_factor.urls import urlpatterns as tf_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bank_app.urls')),
    path('', include(tf_urls)),
    path('accounts/', include('django.contrib.auth.urls'))
]

bank_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import CustomUser, Account
from django.core.exceptions import ObjectDoesNotExist


class NewAccountForm(forms.ModelForm):
    class Meta:
        model = Account
        widgets = {
            "user": forms.HiddenInput()
        }
        fields = ["accountName"]
        labels = {
            "accountName": "Name the account"
        }

    def clean(self):
        accountName = self.cleaned_data.get('accountName')
        if Account.objects.filter(accountName=accountName):
            self._errors['accountName'] = self.error_class(['An account with that name already exists.'])
        return self.cleaned_data


class StaffNewAccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ["user", "accountName"]
        labels = {
            "user": "Choose the Customer you are creating an account for",
            "accountName": "Name the account"
        }

    def clean(self):
        customer = self.cleaned_data.get('user')
        accountName = self.cleaned_data.get('accountName')
        if Account.objects.filter(user=customer, accountName=accountName):
            self._errors['accountName'] = self.error_class(['Customer already has an account with that name.'])
        return self.cleaned_data


class NewUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password', 'is_staff')

    # removes help_text from all fields
    def __init__(self, *args, **kwargs):
        super(NewUserForm, self).__init__(*args, **kwargs)
        for fieldname in self.fields:
            self.fields[fieldname].help_text = None

    # check user with entered email or username does not already exists
    def clean(self):
        super().clean()
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if User.objects.filter(email=email):
            self._errors['email'] = self.error_class(['User with entered email already exists'])
        if User.objects.filter(username=username):
            self._errors['username'] = self.error_class(['Username is already in use. Try another one'])
        return self.cleaned_data


class NewCustomUserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('phone', 'rank')

    def clean(self):
        return self.cleaned_data


class TransferForm(forms.Form):
    amount = forms.DecimalField(label='Amount', max_digits=10)
    debit_account = forms.ModelChoiceField(label='Debit Account', queryset=CustomUser.objects.none())
    debit_text = forms.CharField(label='Debit account text', max_length=25)
    credit_account = forms.ModelChoiceField(label='Credit Account', queryset=CustomUser.objects.none())
    credit_text = forms.CharField(label='Credit account text', max_length=25)

    def clean(self):
        super().clean()

        if self.cleaned_data.get('amount') < 0:
            self._errors['amount'] = self.error_class(['Amount must be positive.'])

        return self.cleaned_data


class TransferInternallyForm(forms.Form):
    amount = forms.DecimalField(label='Amount', max_digits=10)
    debit_account = forms.ModelChoiceField(label='Debit Account', queryset=CustomUser.objects.none())
    debit_text = forms.CharField(label='Debit account text', max_length=25)
    credit_account = forms.IntegerField(label='Credit account number')
    credit_text = forms.CharField(label='Credit account text', max_length=25)

    def clean(self):
        super().clean()

        credit_account = self.cleaned_data.get('credit_account')
        try:
            Account.objects.get(pk=credit_account)
        except ObjectDoesNotExist:
            self._errors['credit_account'] = self.error_class(['Credit account does not exist'])

        if self.cleaned_data.get('amount') < 0:
            self._errors['amount'] = self.error_class(['Amount must be positive'])

        return self.cleaned_data


class TransferBankToBankForm(forms.Form):
    amount = forms.DecimalField(label='Amount', max_digits=10)
    debit_account = forms.IntegerField(label='Debit account number')
    debit_text = forms.CharField(label='Debit account text', max_length=25)
    credit_account = forms.IntegerField(label='Credit account number')
    credit_text = forms.CharField(label='Credit account text', max_length=25)

    def clean(self):
        super().clean()

        if self.cleaned_data.get('amount') < 0:
            self._errors['amount'] = self.error_class(['Amount must be positive'])

        return self.cleaned_data


class LoanForm(forms.Form):
    loan_name = forms.CharField(label='Name for loan', max_length=25)
    amount = forms.DecimalField(label='Amount', max_digits=10)

    def clean(self):
        super().clean()

        if self.cleaned_data.get('amount') < 0:
            self._errors['amount'] = self.error_class(['Amount must be positive.'])

bank_app/views.py
from .models import Rank, Loan, CustomUser, Account, Ledger
from django.http import HttpResponseRedirect
from django.shortcuts import render, reverse, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .forms import NewUserForm, NewCustomUserForm, TransferForm, TransferInternallyForm, LoanForm, StaffNewAccountForm, NewAccountForm, TransferBankToBankForm
from django.db import IntegrityError
from django_otp.decorators import otp_required
from .errors import InsufficientFunds
import requests
import uuid
import datetime
import random


@login_required
def index(request):
    if request.user.is_verified():
        if request.user.is_staff:
            return HttpResponseRedirect(reverse('bank_app:staff_portal'))
        else:
            return HttpResponseRedirect(reverse('bank_app:customer_portal'))
    else:
        return HttpResponseRedirect(reverse('two_factor:setup'))


# @otp_required
@login_required
def customerPortal(request):
    if request.user.is_staff:
        return HttpResponseRedirect(reverse('bank_app:staff_portal'))
    else:
        user = request.user.customuser
        accounts = request.user.customuser.accounts
        loans = request.user.customuser.loans

        context = {
            'user': user,
            'accounts': accounts,
            'loans': loans,
        }
        return render(request, 'bank_app/customer_portal.html', context)


# @otp_required
@login_required
def accountDetails(request, pk):
    user = request.user.customuser
    account = get_object_or_404(Account, pk=pk)
    movements = Ledger.objects.filter(account=pk)
    context = {
        'user': user,
        'account': account,
        'movements': movements,
    }
    return render(request, 'bank_app/account_details.html', context)


# @otp_required
@login_required
def createCustomer(request):
    assert request.user.is_staff, 'User needs to be staff to create a new user account'

    if request.method == 'POST':
        new_user_form = NewUserForm(request.POST)
        new_customuser_form = NewCustomUserForm(request.POST)
        if new_user_form.is_valid() and new_customuser_form.is_valid():
            username = new_user_form.cleaned_data['username']
            first_name = new_user_form.cleaned_data['first_name']
            last_name = new_user_form.cleaned_data['last_name']
            email = new_user_form.cleaned_data['email']
            password = new_user_form.cleaned_data['password']
            is_staff = new_user_form.cleaned_data['is_staff']
            phone = new_customuser_form.cleaned_data['phone']
            rank = new_customuser_form.cleaned_data['rank']
            is_superuser = is_staff
            try:
                user = User.objects.create_user(
                    username=username,
                    first_name=first_name,
                    last_name=last_name,
                    email=email,
                    password=password,
                    is_staff=is_staff,
                    date_joined=datetime.datetime.now(),
                    is_superuser=is_superuser,
                )
                CustomUser.objects.create(user=user, rank=rank, phone=phone, isActive=True)
                return staffCustomerView(request, user.pk)
            except IntegrityError:
                context = {
                    'new_user_form': NewUserForm(),
                    'new_customuser_form': NewCustomUserForm(),
                }
                return render(request, 'bank_app/create_customer.html', context)
        else:
            context = {
                'new_user_form': NewUserForm(request.POST),
                'new_customuser_form': NewCustomUserForm(request.POST),
            }
            return render(request, 'bank_app/create_customer.html', context)
    else:
        new_user_form = NewUserForm()
        new_customuser_form = NewCustomUserForm()
        context = {
            'new_user_form': new_user_form,
            'new_customuser_form': new_customuser_form
        }
        return render(request, 'bank_app/create_customer.html', context)


# @otp_required
@login_required
def movementDetails(request, pk):
    user = request.user.customuser
    movement = get_object_or_404(Ledger, pk=pk)
    context = {
        'user': user,
        'movement': movement
    }
    return render(request, 'bank_app/movement_details.html', context)


# @otp_required
@login_required
def createAccount(request):
    if request.user.is_staff:
        if request.method == 'POST':
            form = StaffNewAccountForm(request.POST)
            if form.is_valid():
                instance = form.instance
                Account.objects.create(
                    user=form.cleaned_data['user'],
                    createdBy=request.user,
                    createdAt=datetime.datetime.now(),
                    accountName=form.cleaned_data['accountName'],
                    id=str(random.randint(100000, 999999)),
                    isActive=True,
                    isLoan=False,
                )
                return HttpResponseRedirect(reverse('bank_app:staff_customer_view', args=(instance.user.pk,)))
        else:
            form = StaffNewAccountForm()
        context = {
            'form': form,
        }
        return render(request, 'bank_app/create_account.html', context)
    else:
        if not request.user.is_staff:
            count = request.user.customuser.count_self_created_accounts
            if not count < 5:
                context = {
                    'title': 'Account Creation Limit Reached',
                    'error': "You’ve reached the maximum number of self-created accounts."
                }
                return render(request, 'bank_app/create_account.html', context)
        if request.method == 'POST':
            form = NewAccountForm(request.POST)
            if form.is_valid():
                Account.objects.create(
                    user=request.user,
                    createdBy=request.user,
                    createdAt=datetime.datetime.now(),
                    accountName=form.cleaned_data['accountName'],
                    id=str(random.randint(100000, 999999)),
                    isActive=True,
                    isLoan=False,
                )
                return HttpResponseRedirect(reverse('bank_app:customer_portal'))
        else:
            form = NewAccountForm()
        context = {
            'form': form,
        }
        return render(request, 'bank_app/create_account.html', context)


# @otp_required
@login_required
def transaction_details(request, transactionId):
    credit = Ledger.objects.filter(transactionId=transactionId).first()
    debit = Ledger.objects.filter(transactionId=transactionId).last()
    accounts = request.user.customuser.accounts
    user = request.user.customuser
    total_balance = 0
    for a in accounts:
        balance = a.change_rank
        total_balance += balance
    if user.rank.name == 'Basic':
        if total_balance >= 0:
            user.rank.value = 20
            user.save()

    loans = request.user.customuser.loans
    for lo in loans:
        if lo.balance == 0:
            lo.isActive = False
            lo.save()

    context = {
        'credit': credit,
        'debit': debit,
    }

    return render(request, 'bank_app/transaction_details.html', context)


# @otp_required
@login_required
def make_transfer(request):
    if request.user.is_staff:
        return HttpResponseRedirect(reverse('bank_app:staff_portal'))
    elif request.method == 'POST':
        form = TransferForm(request.POST)
        form.fields['debit_account'].queryset = request.user.customuser.accounts
        form.fields['credit_account'].queryset = request.user.customuser.accounts_and_loans
        if form.is_valid():
            amount = form.cleaned_data['amount']
            debit_account = Account.objects.get(pk=form.cleaned_data['debit_account'].pk)
            debit_text = form.cleaned_data['debit_text']
            credit_account = Account.objects.get(pk=form.cleaned_data['credit_account'].pk)
            credit_text = form.cleaned_data['credit_text']
            try:
                print(debit_account)
                transfer = Ledger.transfer(amount, debit_account, debit_text, credit_account, credit_text)
                return transaction_details(request, transfer)
            except InsufficientFunds:
                context = {
                    'title': 'Transfer Error',
                    'error': 'Insufficient funds for transfer'
                }
                return render(request, 'bank_app/error.html', context)
    else:
        form = TransferForm()
        form.fields['debit_account'].queryset = request.user.customuser.accounts
        form.fields['credit_account'].queryset = request.user.customuser.accounts_and_loans
        context = {
            'form': form,
        }
        return render(request, 'bank_app/make_transfer.html', context)


# @otp_required
@login_required
def internal_transfer(request):
    assert not request.user.is_staff, 'Staff user routing customer view'

    if request.method == 'POST':
        form = TransferInternallyForm(request.POST)
        form.fields['debit_account'].queryset = request.user.customuser.accounts
        if form.is_valid():
            amount = form.cleaned_data['amount']
            debit_account = Account.objects.get(pk=form.cleaned_data['debit_account'].pk)
            debit_text = form.cleaned_data['debit_text']
            credit_account = Account.objects.get(pk=form.cleaned_data['credit_account'])
            credit_text = form.cleaned_data['credit_text']
            try:
                transfer = Ledger.transfer(amount, debit_account, debit_text, credit_account, credit_text)
                return transaction_details(request, transfer)
            except InsufficientFunds:
                context = {

bank_app/templates/bank_app/account_creation_error.html
{% extends "base.html" %}

{% block main %}
<h3>{{ title }}</h3>
<p>{{ error }}</p>
{% endblock main %}

bank_app/templates/bank_app/account_details.html
{% extends "base.html" %}

{% block main %}
    <body>
        <h3>{{ account.accountName }}</h3>
        <table>
            <tr>
                <th><h4>Current Balance:</h4></th>
            </tr>
            <tr>
                <td><h1>$ {{ account.balance|floatformat:"2" }}</h1></td>
            </tr>
        </table>

        <details>
            <summary>
                Account Details
            </summary>
            <p>
            <table>
                <tr>
                    <th>Account Name</th>
                    <th>Account Owner</th>
                    <th>Account Number</th>
                </tr>
                <tr>
                    <td>{{ account.accountName }}</td>
                    <td>{{ user.user.first_name }} {{ user.user.last_name }}</td>
                    <td>{{ account.id }}</td>
                </tr>
            </table>
            </p>
        </details>

        <h3>Latest Transactions</h3>

        {% if movements %}
        <table>
            <tr>
                <th>Date</th>
                <th>Description</th>
                <th>Amount</th>
            </tr>
            {% for movement in movements %}
            <tr>
                <td>{{ movement.createdAt|date:"d-m-Y" }}</td>
                <td><a href="{% url 'bank_app:movement_details' movement.pk %}">{{ movement.text }}</a></td>
                <td>$ {{ movement.amount }}</td>
            </tr>
            {% endfor %}
        </table>
        {% endif %}
        {% if not movements %}
        <p>Any activity on your account will be shown here.</p>
        {% endif %}
    </body>
{% endblock main %}

bank_app/templates/bank_app/create_account.html
{% extends "base.html" %}

{% block main %}
<body>
    <h3>{{ title }}</h3>
    <p>{{ error }}</p>
    <h3>Create Account</h3>
    <form action="{% url 'bank_app:create_account' %}" method="post">
        {% csrf_token %}
        <fieldset>
            {{ form }}
            <button>Create Account</button>
        </fieldset>
    </form>
</body>
{% endblock main %}
{% block footer %}
{% endblock footer %}

bank_app/templates/bank_app/customer_portal.html
{% extends "base.html" %}

{% block main %}
<h3>Welcome to your overview, {{ user.user.first_name }}.</h3>
<h4>User Details</h4>
<table>
    <tr>
        <th>Full Name</th>
        <td>{{ user.full_name }}</td>
    </tr>
    <tr>
        <th>Rank</th>
        <td>{{ user.rank.name }}</td>
    </tr>
</table>

{% if accounts %}
<h4>Accounts</h4>
<table>
    <tr>
        <th>Description</th>
        <th>Balance</th>
    </tr>
    {% for account in accounts %}
    <tr>
        <td><a href="{% url 'bank_app:account_details' account.pk %}">{{ account.accountName }}</a></td>
        <td>$ {{ account.balance|floatformat:"2" }}</td>
    </tr>
    {% endfor %}
</table>
{% endif %}

{% if loans %}
<h4>Loans</h4>
<table>
    <tr>
        <th>Description</th>
        <th>Balance</th>
    </tr>
    {% for loan in loans %}
    <tr>
        <td><a href="{% url 'bank_app:account_details' loan.pk %}">{{ loan.accountName }}</a></td>
        <td>$ {{ loan.balance|floatformat:"2" }}</td>
    </tr>
    {% endfor %}
</table>
{% endif %}
{% endblock main %}

bank_app/templates/bank_app/error.html
{% extends "base.html" %}

{% block main %}

<p>Welcome, {% if user.is_staff %}{{ user.username }}{% else %}{{ user.customuser.full_name }}{% endif %}.</p>

<h3>{{ title }}</h3>

<p>{{ error }}</p>

{% endblock main %}

bank_app/templates/bank_app/internal_transfer.html
{% extends "base.html" %}

{% block main %}
<h3>Create Transfer</h3>
<h4>Which type of account would you like to transfer to?</h4>
<div>
    <li><a href="{% url 'bank_app:make_transfer' %}"><button>Between Own Accounts</button></a></li>
    <li><a href="#"><button>Omega Bank Account</button></a></li>
    <li><a href="{% url 'bank_app:bank_to_bank_transfer' %}"><button>External Bank Account</button></a></li>
</div>

<h4>Transfer to another account in Omega Bank:</h4>
<form action="{% url 'bank_app:internal_transfer' %}" method="post">
    {% csrf_token %}
    <fieldset>
        {{ form }}
        <button>Transfer</button>
    </fieldset>
</form>
{% endblock main %}

bank_app/templates/bank_app/make_transfer.html
{% extends "base.html" %}

{% block main %}
<h3>Create Transfer</h3>
<h4>Which type of account would you like to transfer to?</h4>
<div>
    <li><a href="#"><button>Between Own Accounts</button></a></li>
    <li><a href="{% url 'bank_app:internal_transfer' %}"><button>Omega Bank Account</button></a></li>
    <li><a href="{% url 'bank_app:bank_to_bank_transfer' %}"><button>External Bank Account</button></a></li>
</div>

<h4>Transfer between your own accounts:</h4>
<form action="{% url 'bank_app:make_transfer' %}" method="post">
    {% csrf_token %}
    <fieldset>
        {{ form }}
        <button>Transfer</button>
    </fieldset>
</form>
{% endblock main %}

bank_app/templates/bank_app/movement_details.html
{% extends "base.html" %}

{% block main %}
<body>
    <h3>Summary of Movement Details</h3>
    <table>
        <tr>
            <th>Amount</th>
            <td>$ {{ movement.amount }}</td>
        </tr>
        <tr>
            <th>Description</th>
            <td>{{ movement.text }}</td>
        </tr>
        <tr>
            <th>Account</th>
            <td>{{ movement.account.accountName }}</td>
        </tr>
        <tr>
            <th>Date</th>
            <td>{{ movement.createdAt|date:"d-m-Y" }}</td>
        </tr>
        <tr>
            <th>ID</th>
            <td>{{ movement.pk }}</td>
        </tr>
    </table>
</body>
{% endblock main %}

bank_app/templates/bank_app/staff_approve_loans.html
{% extends "base.html" %}

{% block main %}
<h3>Approve Loans</h3>
<table>
    <tr>
        <th>Description</th>
        <th>Applicant</th>
        <th>Amount</th>
        <th>Status</th>
    </tr>
    {% for loan in loans %}
    {% if not loan.approved and not loan.declined %}
    <form action="" method="post">
        {% csrf_token %}
        <tr>
            <td>{{ loan.accountName }}</td>
            <td>{{ loan.user.customuser.full_name }}</td>
            <td>{{ loan.amount }}</td>
            <td><a href={% url 'bank_app:approve' loan.pk %}>Approve</a> | <a href={% url 'bank_app:decline' loan.pk %}>Decline</a></td>
        </tr>
    </form>
    {% endif %}
    {% endfor %}
</table>
{% endblock main %}

bank_app/templates/bank_app/staff_customer_view.html
{% extends "base.html" %}

{% block main %}
<h4>Customer Details</h4>
<table>
    <tr>
        <th>Full Name</th>
        <td>{{ user.full_name }}</td>
    </tr>
    <tr>
        <th>Member since</th>
        <td>{{ user.user.date_joined }}</td>
    </tr>
    <tr>
        <th>Phone</th>
        <td>{{ user.phone }}</td>
    </tr>
    <tr>
        <th>E-mail</th>
        <td>{{ user.user.email }}</td>
    </tr>
    <tr>
        <th>Rank</th>
        <td>
            <select name="rank_value" hx-target="body" hx-patch="{% url 'bank_app:staff_customer_view' user.pk %}" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
                {% for rank in ranks %}
                {% if rank.name == user.rank.name %}
                <option value="{{ rank }}" selected>{{ rank.name }}</option>
                {% else %}
                <option value="{{ rank }}">{{ rank.name }}</option>
                {% endif %}
                {% endfor %}
            </select>
        </td>
    </tr>
    <tr>
        <th>Is Active</th>
        <td>
            <select name="active_value" hx-target="body" hx-patch="{% url 'bank_app:staff_customer_view' user.pk %}" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
                <option value="{{ user.isActive }}">{{ user.isActive }}</option>
                {% if user.isActive == True %}
                <option value="False">False</option>
                {% else %}
                <option value="True">True</option>
                {% endif %}
            </select>
        </td>
    </tr>
</table>

{% if accounts %}
<h4>Customer Accounts</h4>
<table>
    <tr>
        <th>Description</th>
        <th>Balance</th>
        <th>Status</th>
    </tr>
    {% for account in accounts %}
    <tr>
        <td><a href="{% url 'bank_app:account_details' account.pk %}">{{ account.accountName }}</a></td>
        <td>$ {{ account.balance|floatformat:"2" }}</td>
        <td>
            <select name="remove_account_{{ account.pk }}" hx-target="body" hx-confirm="Are you sure you want to make this account inactive?" hx-patch="{% url 'bank_app:staff_customer_view' user.pk %}" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
                <option selected>Active</option>
                <option value="{{ account.pk }}">Inactive</option>
            </select>
        </td>
    </tr>
    {% endfor %}
</table>
{% endif %}

{% if loans %}
<h4>Customer Loans</h4>
<table>
    <tr>
        <th>Description</th>
        <th>Balance</th>
        <th>Status</th>
    </tr>
    {% for loan in loans %}
    <tr>
        <td><a href="{% url 'bank_app:account_details' loan.pk %}">{{ loan.accountName }}</a></td>
        <td>$ {{ loan.balance|floatformat:"2" }}</td>
        <td>
            <select name="remove_account_{{ loan.pk }}" hx-target="body" hx-patch="{% url 'bank_app:staff_customer_view' user.pk %}" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
                <option selected>Active</option>
                <option value="{{ loan.pk }}">Inactive</option>
            </select>
        </td>
    </tr>
    {% endfor %}
</table>
{% endif %}

{% endblock main %}

bank_app/templates/bank_app/staff_portal.html
{% extends "base.html" %}

{% block main %}
<h3>Search</h3>
<fieldset>
    <label>Find customer</label>
    <input name="search"
           placeholder="Search for customer"
           class="form-control"
           type="text"
           hx-post="{% url 'bank_app:staff_search' %}"
           hx-trigger="keyup changed delay:500ms"
           hx-target="#search-results"
           hx-indicator=".htmx-indicator"
    />
    {% csrf_token %}
</fieldset>

<table>
    <thead>
        <th>Name</th>
        <th>Phone</th>
        <th>E-mail</th>
    </thead>
    <tbody id="search-results"></tbody>
</table>

{% endblock main %}

bank_app/templates/bank_app/staff_search.html
{% for customer in customers %}
<tr>
    <td><a href="{% url 'bank_app:staff_customer_view' customer.pk %}">{{ customer.full_name }}</a></td>
    <td>{{ customer.phone }}</td>
    <td>{{ customer.user.email }}</td>
</tr>
{% endfor %}

bank_app/templates/bank_app/take_loan.html
{% extends "base.html" %}

{% block main %}
<form action="{% url 'bank_app:take_loan' %}" method="post">
    {% csrf_token %}
    <fieldset>
        {{ form }}
        <button>Apply for Loan</button>
    </fieldset>
</form>
{% endblock main %}

bank_app/templates/bank_app/transaction_details.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name='Omega Bank' content='Welcome to Omega Banking.' />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css"/>
        <title>Omega Bank – Transaction Details</title>
    </head>
    <body>
        <h2>Omega Bank – Transaction Details</h2>
        <hr/>
        <h3>Summary of your transaction:</h3>
        <table>
            <tr>
                <th>Amount</th>
                <td>$ {{ debit.amount }}</td>
            </tr>
            <tr>
                <th>Debit Account</th>
                <td>{{ debit.account.accountName }}</td>
            </tr>
            <tr>
                <th>Debit Description</th>
                <td>{{ debit.text }}</td>
            </tr>
            <tr>
                <th>Credit Account</th>
                <td>{{ credit.account.accountName }}</td>
            </tr>
            <tr>
                <th>Credit Description</th>
                <td>{{ credit.text }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ debit.createdAt|date:"d-m-Y" }}</td>
            </tr>
            <tr>
                <th>ID</th>
                <td>{{ debit.pk }}</td>
            </tr>
        </table>
        <footer>
            <a href="{% url 'bank_app:customer_portal' %}"><button>Back to Overview</button></a>
            <a href="{% url 'logout' %}"><button>Log Out</button></a>
            <table>
                <tr>
                    <td><p>Omega Bank Global</p></td>
                    <td><p>Copenhagen · Denmark</p></td>
                    <td><p>Copyright 2023</p></td>
                </tr>
            </table>
        </footer>
    </body>
</html>