bank_app/urls.py
from django.urls import path
from . import views
from .api import BankToBankTransfer
from django.views.generic import RedirectView

app_name = 'bank_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('customer/', views.customerPortal, name='customer_portal'),
    path('<int:pk>/', views.accountDetails, name='account_details'),
    path('movement/<int:pk>/', views.movementDetails, name='movement_details'),
    path('create_account/', views.createAccount, name='create_account'),
    path('staff_customer_view/<int:pk>/', views.staffCustomerView, name='staff_customer_view'),
    path('create_customer/', views.createCustomer, name='create_customer'),
    # redirect to customer view when two-factor is complete
    path('account/two_factor/setup/complete/', RedirectView.as_view(url='/customer/')),
    path('make_transfer/', views.make_transfer, name='make_transfer'),
    path('internal_transfer', views.internal_transfer, name='internal_transfer'),
    path('bank_to_bank_transfer', views.bank_to_bank_transfer, name='bank_to_bank_transfer'),
    path('transaction_details/<int:transactionId>/', views.make_transfer, name='transaction_details'),
    path('staff_portal/', views.staffPortal, name='staff_portal'),
    path('staff_search/', views.staffSearch, name='staff_search'),
    path('take_loan/', views.take_loan, name='take_loan'),
    path('approve_loans/', views.approve_loan, name='staff_approve_loans'),
    path('approve/<int:pk>/', views.approve, name='approve'),
    path('decline/<int:pk>/>', views.decline, name='decline'),
    path('api/bank_to_bank/', BankToBankTransfer.as_view()),
]

bank_project/urls.py
from django.contrib import admin
from django.urls import path, include
from two_factor.urls import urlpatterns as tf_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bank_app.urls')),
    path('', include(tf_urls)),
    path('accounts/', include('django.contrib.auth.urls'))
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name='Omega Bank' content='Welcome to the world of Omega Banking.' />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <script src="https://unpkg.com/htmx.org@1.9.0" integrity="sha384-aOxz9UdWG0yBiyrTwPeMibmaoq07/d3a96GCbb9x60f3mOt5zwkjdbcHFnKH8qls" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css" />
        {% load static %}
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}" />
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}" />
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />
        <title>Omega Bank</title>
    </head>

    <body>
        <header>
            {% if user.is_staff %}
            <h2>Omega Bank – Staff Portal</h2>
            {% else %}
            <h2>Omega Bank – Customer Portal</h2>
            {% endif %}
        </header>
        <br />
        <hr />
        <nav>
            {% if user.is_staff %}
            <a href="{% url 'bank_app:staff_portal' %}"><button>Search</button></a>
            <a href="{% url 'bank_app:create_customer' %}"><button>Create User</button></a>
            <a href="{% url 'bank_app:create_account' %}"><button>Create Account</button></a>
            <a href="{% url 'bank_app:staff_approve_loans' %}"><button>Approve Loans</button></a>
            {% elif not user.is_staff %}
            <a href="{% url 'bank_app:customer_portal' %}"><button>Overview</button></a>
            <a href="{% url 'bank_app:make_transfer' %}"><button>Create Transfer</button></a>
            <a href="{% url 'bank_app:create_account' %}"><button>Create Account</button></a>
            {% if user.rank.value >= 20 %}
            <a href="{% url 'bank_app:take_loan' %}"><button>Apply for Loan</button></a>
            {% endif %}
            {% if "movement" in request.path %}
            <a href="{% url 'bank_app:account_details' movement.account.id %}"><button>Go back to {{ movement.account.accountName }}</button></a>
            {% endif %}
            {% endif %}
        </nav>
        <hr />
        <main>
            {% block main %}
            {% endblock main %}
        </main>
        <footer>
            <a href="{% url 'logout' %}"><button>Log Out</button></a>
            <table>
                <tr>
                    <td><p>Omega Bank Global</p></td>
                    <td><p>Copenhagen · Denmark</p></td>
                    <td><p>Copyright 2023</p></td>
                </tr>
            </table>
        </footer>
        <script src="https://unpkg.com/htmx.org@1.5.0" integrity="sha384-oGA+prIp5Vchu6we2YkI51UtVzN9Jpx2Z7PnR1I78PnZlN8LkrCT4lqqqmDkyrvI" crossorigin="anonymous"></script>

        <script>
            document.body.addEventListener('htmx:configRequest', (event) => {
                event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
            })
        </script>
    </body>
</html>